### GET request to example server
GET http://localhost:8080/todo

### POST request to add a TODO
POST http://localhost:8080/todo
Content-Type: application/json

{
  "item": "go shopping"
}

### GET request to search TODO
GET http://localhost:8080/search?q=shop


### DELETE request to remove an item
DELETE http://localhost:8080/todo/2
